// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace StravaDiscordBot.Workers.Clients.DiscordApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SendTextMessageRequest
    {
        /// <summary>
        /// Initializes a new instance of the SendTextMessageRequest class.
        /// </summary>
        public SendTextMessageRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SendTextMessageRequest class.
        /// </summary>
        public SendTextMessageRequest(string text = default(string))
        {
            Text = text;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "text")]
        public string Text { get; set; }

    }
}
