apiVersion: apps/v1
kind: Deployment
metadata:
  name: strava-discord-bot-workers-service
spec:
  replicas: 1
  strategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: strava-discord-bot-workers-service
  template:
    metadata: 
      labels:
        app: strava-discord-bot-workers-service
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/connect-service-upstreams': '{{ .Values.global.consul.leaderboard_api.name }}:{{ .Values.global.consul.leaderboard_api.port }},{{ .Values.global.consul.participant_api.name }}:{{ .Values.global.consul.participant_api.port }},{{ .Values.global.consul.discord_api.name }}:{{ .Values.global.consul.discord_api.port }}'
    spec:
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        # Environment variable section
        env:
        {{- $env := merge (.Values.env | default dict) (.Values.global.env | default dict) -}}
        {{ range $k, $v := $env }}
          - name: {{ $k | quote }}
            value: {{ $v | quote }}
        {{- end }}
