apiVersion: apps/v1
kind: Deployment
metadata:
  name: strava-discord-bot-discord-service
 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strava-discord-bot-discord-service
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: strava-discord-bot-discord-service
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/connect-service-upstreams': '{{ .Values.global.consul.leaderboard_api.name }}:{{ .Values.global.consul.leaderboard_api.port }},{{ .Values.global.consul.participant_api.name }}:{{ .Values.global.consul.participant_api.port }}'
    spec:
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        startupProbe:
          httpGet:
            path: /health/startup
            port: 80
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 80
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 80
          successThreshold: 3
        
        # Environment variable section
        env:
        {{- $env := merge (.Values.env | default dict) (.Values.global.env | default dict) -}}
        {{ range $k, $v := $env }}
          - name: {{ $k | quote }}
            value: {{ $v | quote }}
        {{- end }}