// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace StravaDiscordBot.DiscordApi.Clients.LeaderboardApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class LeaderboardResultViewModel
    {
        /// <summary>
        /// Initializes a new instance of the LeaderboardResultViewModel class.
        /// </summary>
        public LeaderboardResultViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LeaderboardResultViewModel class.
        /// </summary>
        public LeaderboardResultViewModel(IList<SubCategoryResultViewModel> categoryResults = default(IList<SubCategoryResultViewModel>))
        {
            CategoryResults = categoryResults;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "categoryResults")]
        public IList<SubCategoryResultViewModel> CategoryResults { get; set; }

    }
}
