// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace StravaDiscordBot.ParticipantApi.Clients.DiscordApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class FieldViewModel
    {
        /// <summary>
        /// Initializes a new instance of the FieldViewModel class.
        /// </summary>
        public FieldViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FieldViewModel class.
        /// </summary>
        public FieldViewModel(string name = default(string), object value = default(object), bool? inline = default(bool?))
        {
            Name = name;
            Value = value;
            Inline = inline;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public object Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "inline")]
        public bool? Inline { get; set; }

    }
}
