name: "Helm Dry-Run"

on:
  push:
    branches:
      - master

jobs:
  helm:
    name: "Dry-Run"
    runs-on: ubuntu-latest
    steps:
      - name: "Setup kube config"
        run: |
          mkdir -p ~/.kube/
          touch ~/.kube/config
          echo -e "${{ secrets.KUBE_CONFIG }}" >> ~/.kube/config

      - name: "Dry Run - Nginx Ingress"
        run: |
          ls
          echo "${PWD}"
          helm dep build helm/nginx-ingress
          CMD_OUTPUT=$(echo helm upgrade --dry-run --install --namespace nginx-ingress nginx-ingress helm/nginx-ingress)
          echo "${CMD_OUTPUT}"
          helm upgrade --dry-run --install --namespace nginx-ingress nginx-ingress helm/nginx-ingress
