name: "Helm Dry-Run"

on:
  pull_request:

jobs:
  helm:
    name: "Dry-Run"
    runs-on: ubuntu-latest
    steps:
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0
      - name: "Setup kube config"
        run: |
          mkdir -p ~/.kube/
          touch ~/.kube/config
          echo -e "${{ secrets.KUBE_CONFIG }}" >> ~/.kube/config

      - name: "Dry Run - Nginx Ingress"
        run: |
          helm dep build helm/nginx-ingress
          helm upgrade --dry-run --install nginx-ingress helm/nginx-ingress

      - name: "Dry Run - Kubernetes Dashboard"
        run: |
          helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
          helm upgrade --dry-run --install k8s-dashboard kubernetes-dashboard/kubernetes-dashboard -f ./helm/dashboard/values.yaml

      - name: "Dry Run - Loki + Promtail"
        run: |
          helm dep build helm/loki
          helm dep build helm/promtail
          helm upgrade --dry-run --install loki helm/loki
          helm upgrade --dry-run --install promtail helm/promtail

      - name: "Dry Run - Prometheus"
        run: |
          helm dep build helm/prometheus
          helm upgrade --dry-run --install prometheus helm/prometheus

      - name: "Dry Run - Grafana"
        run: |
          helm dep build helm/grafana
          helm upgrade --dry-run --install grafana helm/grafana
