name: "Helm Install"

on:
  release:
    types: [published]

jobs:
  helm:
    name: "Dry-Run"
    runs-on: ubuntu-latest
    steps:
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0
      - name: "Setup kube config"
        run: |
          mkdir -p ~/.kube/
          touch ~/.kube/config
          echo -e "${{ secrets.KUBE_CONFIG }}" >> ~/.kube/config

      - name: "Dry Run - Nginx Ingress"
        run: |
          helm dep build helm/nginx-ingress
          helm upgrade --install --namespace nginx-ingress nginx-ingress helm/nginx-ingress
