name: "Helm Install"

on:
  release:
    types: [published]

jobs:
  helm:
    name: "Helm Install"
    runs-on: ubuntu-latest
    steps:
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0
      - name: "Setup kube config"
        run: |
          mkdir -p ~/.kube/
          touch ~/.kube/config
          echo -e "${{ secrets.KUBE_CONFIG }}" >> ~/.kube/config

      - name: "Install - Nginx Ingress"
        run: |
          helm dep build helm/nginx-ingress
          helm upgrade --install nginx-ingress helm/nginx-ingress

      - name: "Install - Kubernetes Dashboard"
        run: |
          helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
          helm upgrade --install k8s-dashboard kubernetes-dashboard/kubernetes-dashboard -f ./helm/dashboard/values.yaml
