name: "Terraform Apply"

on:
  push:
    branches:
      - master

jobs:
  helm:
    name: "Helm"
    runs-on: ubuntu-latest
    steps:
      - name: "Setup kube config"
        run: |
          mkdir -p ~/.kube/
          touch ~/.kube/config
          echo -e "${{ secrets.KUBE_CONFIG }}" >> ~/.kube/config

      - name: "Test list helm"
        run: kubectl cluster-info